# Generated by Django 3.1.3 on 2020-12-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtname', models.CharField(max_length=10, unique=True, verbose_name='类别')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50, unique=True, verbose_name='商品名称')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('gcount', models.IntegerField(default=1, verbose_name='库存')),
                ('gintro', models.CharField(max_length=500, verbose_name='商品简介')),
                ('gstate', models.CharField(choices=[('on', '在售'), ('out', '售空')], default='在售', max_length=10, verbose_name='商品状态')),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_goods.goodtype', verbose_name='类别')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
